name: User Service CI

on:
  push:
    branches: [ "master" ]
    paths: 
      - 'services/user-service/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'services/user-service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      working-directory: ./services/user-service
      run: npm install
    
    - name: Run unit tests
      working-directory: ./services/user-service
      run: npm test
      env:
        NODE_ENV: test
    
    - name: Run security audit
      working-directory: ./services/user-service
      run: npm audit --production
    
  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push Docker image
      working-directory: ./services/user-service
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:${{ github.sha }}